# Generated by Django 3.0.5 on 2020-07-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('word', models.CharField(db_index=True, max_length=80, primary_key=True, serialize=False)),
                ('definition', models.CharField(max_length=480)),
            ],
        ),
    ]
